apiVersion: v1
kind: PersistentVolume
metadata:
  name: gosvrlocal-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  claimRef:
    namespace: default
    name: goserver-pv-claim
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data01
---
