apiVersion: v1
kind: Service
metadata:
  name: contacts-api
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: contacts-api
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: contacts-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contacts-api
    spec:
      containers:
        - name: contacts-api
          image: senthilrajar/devopsbyexample:contacts-api
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: contacts
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: password
          ports:
            - containerPort: 3000