apiVersion: v1
kind: ReplicationController
metadata:
  name: contacts-api-VERSION
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: contacts-api-VERSION
    spec:
      containers:
        - name: contacts-api-VERSION
          image: senthilrajar/devopsbyexample:contacts-api
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: contacts
            - name: DB_USERNAME
              value: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-pass
                  key: password
          ports:
            - containerPort: 3000