apiVersion: v1
kind: Service
metadata:
  name: contacts-ui
spec:
  ports:
  - name: npm
    port: 3000
    targetPort: 3000
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: contacts-ui
  type: NodePort