apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: postgres-pv-claim
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/data/pv-1