apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    type: local
  # annotations:
  #   "helm.sh/hook": pre-install
spec:
  capacity:
    storage: {{ .Values.storageSize }}
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: {{ .Values.claimName }}
  persistentVolumeReclaimPolicy: {{ .Values.claimPolicy }}
  hostPath:
    path: {{ .Values.volumePath }}